name: Run Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./plugfest-2020

    strategy:
      # will not stop all tests if one vendor's tests fail
      fail-fast: false
      matrix:
        node-version: [12.x]
        vendor:
          - transmute
          - digital_bazaar
          - danubetech
          - mavennet
          - trustbloc
          - factom
          - sicpa
          - dock

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install project
        working-directory: ${{ env.working-directory }}
        run: npm install

      - name: Lint project
        working-directory: ${{ env.working-directory }}
        run: npm run lint

      - name: Run tests
        working-directory: ${{ env.working-directory }}
        run: INTEROP_FOCUS=${{ matrix.vendor}} npm run test
